'use strict';

// Tests for the memory seam: `crag memory` command (register/config shape,
// subcommand validation, status against a dead backend) and the audit
// memory axis (offline .gen annotation parsing + retired-diff, and the
// `crag audit` integration: advisory-only, JSON fields, exit-code neutrality).

const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

function test(name, fn) {
  try {
    fn();
    console.log(`  \x1b[32m\u2713\x1b[0m ${name}`);
  } catch (err) {
    console.error(`  \x1b[31m\u2717\x1b[0m ${name}`);
    console.error(`    ${err.message}`);
    process.exitCode = 1;
  }
}

const crag = path.join(__dirname, '..', 'bin', 'crag.js');

function run(args, opts = {}) {
  return execFileSync(process.execPath, [crag, ...args], {
    encoding: 'utf-8',
    timeout: 15000,
    stdio: ['pipe', 'pipe', 'pipe'],
    env: { ...process.env, CRAG_NO_UPDATE_CHECK: '1' },
    ...opts,
  });
}

function tmpdir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'crag-memseam-'));
}

// Isolate the USER layer (~/.crag/governance.gen.md): resolveHome() honors
// process.env.HOME at call time, so point it at an empty temp home for both
// in-process library calls and CLI subprocesses — otherwise a real user-layer
// .gen on the dev machine pollutes rule counts.
const FAKE_HOME = tmpdir();
function withFakeHome(fn) {
  const prev = process.env.HOME;
  process.env.HOME = FAKE_HOME;
  try { return fn(); } finally {
    if (prev === undefined) delete process.env.HOME; else process.env.HOME = prev;
  }
}
const HOME_ENV = { HOME: FAKE_HOME };

// ── crag memory: register + config shape ────────────────────────────────

test('memory register writes top-level stdio config loadMemoryConfig understands', () => {
  const cwd = tmpdir();
  run(['memory', 'register'], { cwd });
  const cfg = JSON.parse(fs.readFileSync(path.join(cwd, '.crag', 'mcp.json'), 'utf-8'));
  assert.strictEqual(cfg.command, 'crag-anchor');
  assert.deepStrictEqual(cfg.args, ['mcp']);
  // Must round-trip through the real loader as a stdio backend.
  const { loadMemoryConfig } = require('../src/mcp/config');
  const loaded = loadMemoryConfig(cwd);
  assert.ok(loaded, 'loadMemoryConfig returned null for registered config');
  assert.strictEqual(loaded.kind, 'stdio');
  assert.strictEqual(loaded.command, 'crag-anchor');
});

test('memory register is idempotent', () => {
  const cwd = tmpdir();
  run(['memory', 'register'], { cwd });
  run(['memory', 'register'], { cwd }); // second run must not throw
  const cfg = JSON.parse(fs.readFileSync(path.join(cwd, '.crag', 'mcp.json'), 'utf-8'));
  assert.strictEqual(cfg.command, 'crag-anchor');
});

test('memory register refuses to clobber a different backend without --force', () => {
  const cwd = tmpdir();
  fs.mkdirSync(path.join(cwd, '.crag'), { recursive: true });
  fs.writeFileSync(path.join(cwd, '.crag', 'mcp.json'),
    JSON.stringify({ url: 'http://elsewhere:9999' }), 'utf-8');
  assert.throws(() => run(['memory', 'register'], { cwd }), /already configures|force/i);
  // With --force it overwrites.
  run(['memory', 'register', '--force'], { cwd });
  const cfg = JSON.parse(fs.readFileSync(path.join(cwd, '.crag', 'mcp.json'), 'utf-8'));
  assert.strictEqual(cfg.command, 'crag-anchor');
});

test('memory rejects unknown subcommand', () => {
  const cwd = tmpdir();
  assert.throws(() => run(['memory', 'bogus'], { cwd }), /unknown subcommand/i);
});

test('memory status exits 1 when engine is down', () => {
  const cwd = tmpdir();
  let failed = false;
  try {
    run(['memory', 'status'], { cwd, env: { ...process.env, CRAG_NO_UPDATE_CHECK: '1', CRAG_ANCHOR_URL: 'http://127.0.0.1:1' } });
  } catch (err) {
    failed = true;
    assert.match(String(err.stdout || ''), /DOWN/);
  }
  assert.ok(failed, 'expected non-zero exit for dead engine');
});

// ── audit-gen: offline annotation parsing ───────────────────────────────

const { parseGenFile, auditGenLayers, diffAgainstEligible } = require('../src/distill/audit-gen');

function writeGen(cwd, lines) {
  const dir = path.join(cwd, '.crag');
  fs.mkdirSync(dir, { recursive: true });
  const p = path.join(dir, 'governance.gen.md');
  fs.writeFileSync(p, lines.join('\n') + '\n', 'utf-8');
  return p;
}

test('parseGenFile extracts principle annotations', () => {
  const cwd = tmpdir();
  const p = writeGen(cwd, [
    '<!-- GENERATED by `crag distill` -->',
    '- Always use conventional commits <!-- principle:12 confidence:0.9 scope:project adopted:2026-07-01 -->',
    '- not a managed line',
    '- Never scp configs to the VPS <!-- principle:127 confidence:0.95 scope:project adopted:2026-07-17 -->',
  ]);
  const rules = parseGenFile(p);
  assert.strictEqual(rules.length, 2);
  assert.strictEqual(rules[0].principleId, 12);
  assert.strictEqual(rules[0].adopted, '2026-07-01');
  assert.strictEqual(rules[1].principleId, 127);
  assert.match(rules[1].text, /Never scp configs/);
});

test('auditGenLayers flags stale adoption beyond threshold', () => {
  const cwd = tmpdir();
  writeGen(cwd, [
    '- Old rule <!-- principle:1 confidence:0.9 scope:project adopted:2026-05-01 -->',
    '- New rule <!-- principle:2 confidence:0.9 scope:project adopted:2026-07-15 -->',
  ]);
  const a = withFakeHome(() => auditGenLayers(cwd, new Date('2026-07-17T00:00:00Z')));
  assert.strictEqual(a.present, true);
  assert.strictEqual(a.totalRules, 2);
  assert.strictEqual(a.staleAdoption.length, 1);
  assert.strictEqual(a.staleAdoption[0].principleId, 1);
  assert.ok(a.staleAdoption[0].ageDays > 30);
});

test('diffAgainstEligible reports rendered-but-retired principles', () => {
  const cwd = tmpdir();
  writeGen(cwd, [
    '- Kept <!-- principle:10 confidence:0.9 scope:project adopted:2026-07-17 -->',
    '- Retired <!-- principle:11 confidence:0.9 scope:project adopted:2026-07-17 -->',
  ]);
  const a = withFakeHome(() => auditGenLayers(cwd, new Date('2026-07-17T00:00:00Z')));
  const d = diffAgainstEligible(a, [{ id: 10, text: 'Kept', claim_health: 'fresh' }]);
  assert.strictEqual(d.retired.length, 1);
  assert.strictEqual(d.retired[0].principleId, 11);
  assert.strictEqual(d.eligibleCount, 1);
});

// ── crag audit integration ──────────────────────────────────────────────

function scaffoldGovernance(cwd) {
  const dir = path.join(cwd, '.claude');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'governance.md'), [
    '# governance',
    '',
    '## Quality Gates',
    '',
    '- true  # placeholder',
    '',
  ].join('\n'), 'utf-8');
}

test('audit reports memory axis in JSON without affecting total', () => {
  const cwd = tmpdir();
  scaffoldGovernance(cwd);
  writeGen(cwd, [
    '- Old managed rule <!-- principle:99 confidence:0.9 scope:project adopted:2026-01-01 -->',
  ]);
  const out = run(["audit", "--json"], { cwd, env: { ...process.env, CRAG_NO_UPDATE_CHECK: "1", ...HOME_ENV } });
  const parsed = JSON.parse(out);
  assert.strictEqual(parsed.summary.memoryManagedRules, 1);
  assert.ok(parsed.summary.memoryStaleAdoption >= 1, 'expected stale adoption flag');
  assert.strictEqual(parsed.summary.memoryRetired, 0);
  assert.ok(parsed.memory, 'memory block missing from report');
  // Advisory: memory findings never count toward total.
  assert.strictEqual(parsed.summary.total, 0);
});

test('audit human output shows memory-managed rules section', () => {
  const cwd = tmpdir();
  scaffoldGovernance(cwd);
  writeGen(cwd, [
    '- Managed rule <!-- principle:7 confidence:0.9 scope:project adopted:2026-07-17 -->',
  ]);
  const out = run(["audit"], { cwd, env: { ...process.env, CRAG_NO_UPDATE_CHECK: "1", ...HOME_ENV } });
  assert.match(out, /Memory-managed rules/);
  assert.match(out, /1 rule under management/);
});

test('audit without .gen files stays silent on memory axis', () => {
  const cwd = tmpdir();
  scaffoldGovernance(cwd);
  const out = run(["audit"], { cwd, env: { ...process.env, CRAG_NO_UPDATE_CHECK: "1", ...HOME_ENV } });
  assert.doesNotMatch(out, /Memory-managed rules/);
  const jsonOut = JSON.parse(run(["audit", "--json"], { cwd, env: { ...process.env, CRAG_NO_UPDATE_CHECK: "1", ...HOME_ENV } }));
  assert.strictEqual(jsonOut.summary.memoryManagedRules, 0);
});
