'use strict';

/**
 * render.js — pure text rendering of memory principles into
 * governance.gen.md content. NO LLM, NO network, NO rephrasing: principles
 * arrive from the backend as already-rendered text (any rewriting happens
 * backend-side, before crag ever sees the string). This module only places
 * verbatim text into the governance.gen.md shape, per docs/closed-loop.md
 * REV 5.1: "crag only ever places verbatim principle text."
 */

// Only these claim_health values pass the compile-eligibility gate.
// Anything else (stale, unverified, revalidating, missing) is OMITTED —
// retirement by omission, never an explicit delete.
const ELIGIBLE_CLAIM_HEALTH = new Set(['fresh', 'passing']);

const GEN_BANNER = (asOf) => `<!-- GENERATED by \`crag distill\` on ${asOf} — DO NOT EDIT BY HAND.
     Source: verified memory principles (claim_health: fresh/passing only).
     Regenerate: \`crag distill\`. Preview a would-change diff: \`crag distill --check\`.
     Stale principles are OMITTED automatically (retirement by omission) —
     absence here means the backend no longer considers the rule fresh. -->`;

/**
 * scope -> which .gen layer a principle belongs in.
 * 'universal' -> the user-layer .crag/governance.gen.md
 * anything else ('project', 'stack', missing, ...) -> the project-layer file
 * (fail-safe default: unknown scope never leaks into the shared user layer).
 */
function layerForScope(scope) {
  return scope === 'universal' ? 'user' : 'project';
}

/**
 * Filter to compile-eligible principles (fresh/passing claim_health) and
 * drop anything without the minimum required shape (id + text).
 */
function eligiblePrinciples(principles) {
  if (!Array.isArray(principles)) return [];
  return principles.filter((p) => {
    if (!p || typeof p !== 'object') return false;
    if (typeof p.id === 'undefined' || p.id === null) return false;
    if (typeof p.text !== 'string' || !p.text.trim()) return false;
    return ELIGIBLE_CLAIM_HEALTH.has(p.claim_health);
  });
}

/**
 * Partition eligible principles into { user: [...], project: [...] } by
 * scope, per layerForScope().
 */
function partitionByLayer(principles) {
  const out = { user: [], project: [] };
  for (const p of eligiblePrinciples(principles)) {
    out[layerForScope(p.scope)].push(p);
  }
  return out;
}

/**
 * Render one principle as a single annotated bullet line. The annotation
 * comment carries the source principle id + confidence + adopted date so
 * `crag audit` / compose.js's rot audit can back-link to the source claim
 * (docs/closed-loop.md leak #3: "rules must carry principle+claim IDs").
 */
function renderPrincipleLine(p, adoptedDate) {
  const text = String(p.text).trim().replace(/\n+/g, ' ');
  const confidence = typeof p.confidence === 'number' ? p.confidence.toFixed(2) : 'n/a';
  const scope = p.scope || 'project';
  return `- ${text} <!-- principle:${p.id} confidence:${confidence} scope:${scope} adopted:${adoptedDate} -->`;
}

/**
 * Render a full governance.gen.md body for one layer's principle list.
 * Deterministic ordering: sorted by id ascending so re-running distill on
 * an unchanged principle set produces byte-identical output (stable diffs
 * for the operator's `.gen` review).
 */
function renderGenFile(principles, opts = {}) {
  const asOf = opts.asOf || new Date().toISOString();
  const adoptedDate = asOf.slice(0, 10);
  const sorted = [...principles].sort((a, b) => (a.id > b.id ? 1 : a.id < b.id ? -1 : 0));

  const lines = sorted.map((p) => renderPrincipleLine(p, adoptedDate));
  const body = lines.length > 0 ? lines.join('\n') : '(no compile-eligible principles at this scope)';

  return `${GEN_BANNER(asOf)}

## Distilled Principles

${body}
`;
}

module.exports = {
  ELIGIBLE_CLAIM_HEALTH,
  eligiblePrinciples,
  layerForScope,
  partitionByLayer,
  renderPrincipleLine,
  renderGenFile,
};
