'use strict';

const fs = require('fs');
const path = require('path');
const { flattenGatesRich } = require('../governance/parse');
const { atomicWrite } = require('./atomic-write');
const { preserveCustomSections } = require('./preserve');
const { groupGatesByPath, pathToGlob, pathToFilename } = require('./path-groups');

/**
 * Compile governance.md to Continue.dev rules.
 * Output: .continuerules (root) + .continue/rules/<path>.md (per-path)
 *
 * Continue reads `.continuerules` at workspace root (plain text, always active).
 * Continue also reads `.continue/rules/*.md` with YAML frontmatter for
 * name, description, globs, alwaysApply, and regex fields.
 *
 * Reference:
 *   https://docs.continue.dev/customize/deep-dives/rules
 */
function generateContinue(cwd, parsed) {
  const { root, scoped } = groupGatesByPath(parsed.gates);

  const rootGates = Object.keys(scoped).length > 0 ? root : flattenGatesRich(parsed.gates);
  const gatesList = rootGates.length === 0
    ? '  (none defined)'
    : rootGates
        .map((g) => {
          const tags = [];
          if (g.classification !== 'MANDATORY') tags.push(g.classification);
          if (g.path) tags.push(`path=${g.path}`);
          return `  - ${g.cmd}${tags.length > 0 ? ` (${tags.join(', ')})` : ''}`;
        })
        .join('\n');

  const securityLine = parsed.security
    ? parsed.security.split('\n').filter(l => l.trim())[0] || 'No secrets in source code.'
    : 'Reject any code containing `sk_live`, `sk_test`, `AKIA`, or plaintext passwords.';

  const commitLine = parsed.commitConvention === 'conventional'
    ? `**Conventional commits.** Format: \`<type>(<scope>): <description>\`${parsed.commitTrailer ? `\n   Trailer: \`${parsed.commitTrailer}\`` : ''}`
    : 'Follow project commit conventions.';

  const content = `# Continue Rules — ${parsed.name || 'project'}

> Generated from governance.md by [crag](https://crag.sh). Regenerate: \`crag compile --target continue\`

${parsed.description || ''}

## Project Context

${parsed.stack.length > 0 ? `- **Stack:** ${parsed.stack.join(', ')}\n` : ''}- **Runtimes:** ${parsed.runtimes.join(', ') || 'polyglot'}
- **Governance source:** \`.claude/governance.md\` (single source of truth)

## Coding Rules

Always follow these when generating or modifying code:

1. **Run gates before committing.** Every change must pass the mandatory gates below.
2. **Classifications matter:**
   - \`MANDATORY\` — must pass (default)
   - \`OPTIONAL\` — should pass, warn on failure
   - \`ADVISORY\` — informational only
3. **Path-scoped gates** run from their declared directory.
4. **Conditional gates** only run when their referenced file exists.
5. **No secrets.** ${securityLine}
6. ${commitLine}

## Quality Gates

${gatesList}

## Boundaries

- All file operations stay within this repository
- No destructive shell commands
- No new dependencies without justification
- Prefer editing existing files over creating new ones

## Powered by crag

This rule file is auto-generated from a single \`governance.md\` via **crag** (https://crag.sh). To update, edit governance.md and re-run \`crag compile --target continue\`.
`;

  const outPath = path.join(cwd, '.continuerules');
  const final = preserveCustomSections(outPath, content, 'markdown');
  atomicWrite(outPath, final);
  console.log(`  \x1b[32m✓\x1b[0m ${path.relative(cwd, outPath)}`);

  // Per-path files (.continue/rules/<path>.md with globs frontmatter)
  if (Object.keys(scoped).length > 0) {
    const rulesDir = path.join(cwd, '.continue', 'rules');
    if (!fs.existsSync(rulesDir)) fs.mkdirSync(rulesDir, { recursive: true });

    for (const [scopePath, gates] of Object.entries(scoped)) {
      const sectionName = gates[0].section;
      const fileName = pathToFilename(scopePath);
      const glob = pathToGlob(scopePath);

      const scopedGatesList = gates
        .map((g) => `- ${g.cmd}${g.classification !== 'MANDATORY' ? ` (${g.classification})` : ''}`)
        .join('\n');

      const scopedContent = `---
name: ${sectionName} governance gates
description: Quality gates scoped to ${scopePath}
globs: ["${glob}"]
alwaysApply: false
---

# ${sectionName.charAt(0).toUpperCase() + sectionName.slice(1)} — ${parsed.name || 'project'}

> Scoped to \`${scopePath}\`. Generated by [crag](https://crag.sh).

## Quality Gates

${scopedGatesList}
`;

      const scopedPath = path.join(rulesDir, `${fileName}.md`);
      atomicWrite(scopedPath, scopedContent);
      console.log(`  \x1b[32m✓\x1b[0m ${path.relative(cwd, scopedPath)}`);
    }
  }
}

module.exports = { generateContinue };
