'use strict';

const fs = require('fs');
const path = require('path');
const { flattenGatesRich } = require('../governance/parse');
const { atomicWrite } = require('./atomic-write');
const { preserveCustomSections } = require('./preserve');
const { groupGatesByPath, pathToGlob, pathToFilename } = require('./path-groups');
const { yamlScalar } = require('../update/integrity');

/**
 * Compile governance.md to GitHub Copilot instructions.
 * Output: .github/copilot-instructions.md (+ per-path .github/instructions/*.instructions.md)
 *
 * Copilot reads `.github/copilot-instructions.md` for repo-wide instructions.
 * Copilot also supports `.github/instructions/*.instructions.md` with
 * `applyTo` globs for path-scoped instructions (early 2025+).
 *
 * Reference:
 *   https://docs.github.com/en/copilot/customizing-copilot/adding-custom-instructions-for-github-copilot
 */
function generateCopilot(cwd, parsed) {
  const { root, scoped } = groupGatesByPath(parsed.gates);

  const rootGates = Object.keys(scoped).length > 0 ? root : flattenGatesRich(parsed.gates);
  const gatesBlock = rootGates.length === 0
    ? '_No quality gates defined — add them to governance.md._'
    : rootGates
        .map((g) => {
          const prefix = g.classification !== 'MANDATORY' ? ` (${g.classification.toLowerCase()})` : '';
          const scope = g.path ? ` in \`${g.path}\`` : '';
          return `- **${g.section}**${scope}${prefix}: \`${g.cmd}\``;
        })
        .join('\n');

  const securityBlock = parsed.security
    ? parsed.security
    : 'Never commit values matching `sk_live`, `sk_test`, `AKIA`, or `password = "…"`.';

  const commitLine = parsed.commitConvention === 'conventional'
    ? `5. **Conventional commits** for all changes.${parsed.commitTrailer ? ` Trailer: \`${parsed.commitTrailer}\`` : ''}`
    : '5. Follow project commit conventions.';

  const content = `# Copilot Instructions — ${parsed.name || 'project'}

> Generated from governance.md by crag. Regenerate: \`crag compile --target copilot\`

${parsed.description || ''}
${parsed.stack.length > 0 ? `\n**Stack:** ${parsed.stack.join(', ')}` : ''}

## Runtimes

${parsed.runtimes.length > 0 ? parsed.runtimes.join(', ') : 'polyglot'}

## Quality Gates

When you propose changes, the following checks must pass before commit:

${gatesBlock}

## Expectations for AI-Assisted Code

1. **Run gates before suggesting a commit.** If you cannot run them (no shell access), explicitly remind the human to run them.
2. **Respect classifications.** \`MANDATORY\` gates must pass. \`OPTIONAL\` gates should pass but may be overridden with a note. \`ADVISORY\` gates are informational only.
3. **Respect workspace paths.** When a gate is scoped to a subdirectory, run it from that directory.
4. **No hardcoded secrets.** ${securityBlock}
${commitLine}
6. **Conservative changes.** Do not rewrite unrelated files. Do not add new dependencies without explaining why.

## Tool Context

This project uses **crag** (https://www.npmjs.com/package/@whitehatd/crag) as its AI-agent governance layer. The \`governance.md\` file is the authoritative source. If you have shell access, run \`crag check\` to verify the infrastructure and \`crag diff\` to detect drift.
`;

  const outPath = path.join(cwd, '.github', 'copilot-instructions.md');
  const final = preserveCustomSections(outPath, content, 'markdown');
  atomicWrite(outPath, final);
  console.log(`  \x1b[32m✓\x1b[0m ${path.relative(cwd, outPath)}`);

  // Per-path scoped instructions (.github/instructions/*.instructions.md)
  if (Object.keys(scoped).length > 0) {
    const instrDir = path.join(cwd, '.github', 'instructions');
    if (!fs.existsSync(instrDir)) fs.mkdirSync(instrDir, { recursive: true });

    for (const [scopePath, gates] of Object.entries(scoped)) {
      const sectionName = gates[0].section;
      const fileName = pathToFilename(scopePath);
      const glob = pathToGlob(scopePath);

      const scopedGatesBlock = gates
        .map((g) => {
          const prefix = g.classification !== 'MANDATORY' ? ` (${g.classification.toLowerCase()})` : '';
          return `- \`${g.cmd}\`${prefix}`;
        })
        .join('\n');

      const scopedContent = `---
description: ${yamlScalar(`${sectionName} governance gates for ${parsed.name || 'project'}`)}
applyTo: ${yamlScalar(glob)}
---

# ${sectionName.charAt(0).toUpperCase() + sectionName.slice(1)} — ${parsed.name || 'project'}

> Scoped to \`${scopePath}\`. Generated by crag.

## Quality Gates

${scopedGatesBlock}
`;

      const scopedPath = path.join(instrDir, `${fileName}.instructions.md`);
      atomicWrite(scopedPath, scopedContent);
      console.log(`  \x1b[32m✓\x1b[0m ${path.relative(cwd, scopedPath)}`);
    }
  }
}

module.exports = { generateCopilot };
