'use strict';

const fs = require('fs');
const path = require('path');
const { flattenGates } = require('../governance/parse');
const { atomicWrite } = require('./atomic-write');
const { preserveCustomSections } = require('./preserve');
const { groupGatesByPath, pathToGlob, pathToFilename } = require('./path-groups');

function generateCursorRules(cwd, parsed) {
  const dir = path.join(cwd, '.cursor', 'rules');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const flat = flattenGates(parsed.gates);

  // --- Root file (alwaysApply: true) with unscoped gates ---
  const { root, scoped } = groupGatesByPath(parsed.gates);

  let gatesList = '';
  // Use root gates for the main file; fall back to all gates if no path-scoped sections exist
  const rootFlat = {};
  for (const g of root) {
    (rootFlat[g.section] = rootFlat[g.section] || []).push(g.cmd);
  }
  const gateSource = Object.keys(scoped).length > 0 ? rootFlat : flat;
  for (const [section, cmds] of Object.entries(gateSource)) {
    const items = Array.isArray(cmds) ? cmds : [];
    gatesList += `\n### ${section.charAt(0).toUpperCase() + section.slice(1)}\n`;
    for (const cmd of items) {
      gatesList += `- \`${cmd}\`\n`;
    }
  }

  // Determine globs from runtimes
  const globs = [];
  if (parsed.runtimes.includes('node')) globs.push('"**/*.ts"', '"**/*.tsx"', '"**/*.js"', '"**/*.jsx"');
  if (parsed.runtimes.includes('rust')) globs.push('"**/*.rs"');
  if (parsed.runtimes.includes('python')) globs.push('"**/*.py"');
  if (parsed.runtimes.includes('java')) globs.push('"**/*.java"', '"**/*.kt"');
  if (parsed.runtimes.includes('go')) globs.push('"**/*.go"');
  if (globs.length === 0) globs.push('"**/*"');

  const securityBlock = parsed.security
    ? `\n## Security\n\n${parsed.security}\n`
    : '\n## Security\n\n- No hardcoded secrets — grep for sk_live, AKIA, password= before commit\n';

  const branchBlock = parsed.commitConvention === 'conventional'
    ? `- Conventional commits (feat:, fix:, docs:, etc.)${parsed.commitTrailer ? `\n- Commit trailer: ${parsed.commitTrailer}` : ''}`
    : '- Follow project commit conventions';

  const content = [
    '---',
    `description: Governance rules for ${parsed.name || 'this project'} — quality gates, security, conventions`,
    'globs:',
    ...globs.map(g => `  - ${g}`),
    'alwaysApply: true',
    '---',
    '',
    `# Governance — ${parsed.name || 'Project'}`,
    '',
    `> Generated from governance.md by [crag](https://crag.sh). Regenerate: \`crag compile --target cursor\``,
    '',
    parsed.stack.length > 0 ? `**Stack:** ${parsed.stack.join(', ')}\n` : '',
    '## Quality Gates',
    '',
    'Run these checks in order before committing:',
    gatesList.trim(),
    securityBlock.trim(),
    '',
    '## Conventions',
    '',
    branchBlock,
    `- Runtimes: ${parsed.runtimes.join(', ') || 'auto-detected'}`,
    '',
  ].filter(l => l !== undefined).join('\n');

  const outPath = path.join(dir, 'governance.mdc');
  // Cursor .mdc files have YAML frontmatter — preservation markers would break
  // parsing. Users who need custom rules should create additional .mdc files.
  atomicWrite(outPath, content);
  console.log(`  \x1b[32m✓\x1b[0m ${path.relative(cwd, outPath)}`);

  // --- Per-path files (glob-scoped) ---
  for (const [scopePath, gates] of Object.entries(scoped)) {
    const sectionName = gates[0].section;
    const fileName = pathToFilename(scopePath);
    const glob = pathToGlob(scopePath);

    let scopedGatesList = '';
    for (const g of gates) {
      const tag = g.classification !== 'MANDATORY' ? ` _(${g.classification})_` : '';
      scopedGatesList += `- \`${g.cmd}\`${tag}\n`;
    }

    const scopedContent = [
      '---',
      `description: ${sectionName} gates scoped to ${scopePath}`,
      `globs:`,
      `  - "${glob}"`,
      'alwaysApply: false',
      '---',
      '',
      `# ${sectionName.charAt(0).toUpperCase() + sectionName.slice(1)} — ${parsed.name || 'Project'}`,
      '',
      `> Scoped to \`${scopePath}\`. Generated by [crag](https://crag.sh).`,
      '',
      '## Quality Gates',
      '',
      scopedGatesList.trim(),
      '',
    ].join('\n');

    const scopedPath = path.join(dir, `${fileName}.mdc`);
    atomicWrite(scopedPath, scopedContent);
    console.log(`  \x1b[32m✓\x1b[0m ${path.relative(cwd, scopedPath)}`);
  }
}

module.exports = { generateCursorRules };
