'use strict';

/**
 * detect.js — harness detection (the open-gap differentiator).
 *
 * ruler/rulesync make you list targets by hand (`ruler.toml`, `--targets`).
 * crag DETECTS which harnesses a repo actually uses so `crag compile` writes
 * only the files that matter — not all 23. Detection is layered and follows
 * Anchor's own doctrine (observe, don't assert):
 *
 *   1. Static folder signals — TOOL-OWNED markers (dirs/config files the tool
 *      itself creates), NOT files crag generates. A crag-generated file with a
 *      `crag:auto-start` / "by crag" / "MIRROR of AGENTS.md" marker never counts
 *      as a signal (that would make crag's own output re-enable a tool forever).
 *   2. Machine-installed tools — best-effort `which <bin>`, used as a hint only
 *      (never a hard gate — keeps compile portable/deterministic in CI).
 *   3. Persist + reconcile — the resolved set is written to `.crag/config.json`
 *      and becomes authoritative. Detection re-runs only on first compile or an
 *      explicit refresh, so the result is reproducible and user-editable.
 *
 * Pure fs/child_process — no network, no LLM, no import of the compiler or the
 * memory/distill trees.
 */

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { TARGETS, getTarget } = require('./targets');

// Markers that identify a file as crag-generated (so it is NOT a user signal).
const CRAG_MARKERS = [
  '<!-- crag:auto-start -->',
  'by [crag]',
  'GENERATED MIRROR of AGENTS.md',
  'Generated from governance.md by',
  'Generated by [crag]',
];

const CONFIG_REL = path.join('.crag', 'config.json');

function isCragGenerated(absPath) {
  try {
    if (!fs.statSync(absPath).isFile()) return false;
    const head = fs.readFileSync(absPath, 'utf-8').slice(0, 600);
    return CRAG_MARKERS.some((m) => head.includes(m));
  } catch {
    return false;
  }
}

/**
 * Does a single detect-signal path count as a TOOL-OWNED signal in cwd?
 * Directories count on existence. Files count only if present AND not
 * crag-generated (a crag mirror/stub must not detect its own tool).
 */
function signalPresent(cwd, sig) {
  const abs = path.join(cwd, ...sig.split('/'));
  const isDir = sig.endsWith('/');
  let st;
  try { st = fs.statSync(abs); } catch { return false; }
  if (isDir) return st.isDirectory();
  if (st.isDirectory()) return true; // signal named a dir without trailing slash
  return !isCragGenerated(abs);
}

/**
 * Static folder detection → { toolOwned: Set<id>, byId: {id: [signals]} }.
 */
function staticSignals(cwd) {
  const toolOwned = new Set();
  const byId = {};
  for (const t of TARGETS) {
    if (!Array.isArray(t.detect)) continue;
    const hit = t.detect.filter((sig) => signalPresent(cwd, sig));
    if (hit.length > 0) {
      toolOwned.add(t.id);
      byId[t.id] = hit;
    }
  }
  return { toolOwned, byId };
}

let _installedCache = null;
/**
 * Best-effort: which registry bins are on PATH. Cached per process. Never
 * throws; a missing `which`/`where` just yields an empty set.
 */
function installedTools() {
  if (_installedCache) return _installedCache;
  const found = new Set();
  const whichCmd = process.platform === 'win32' ? 'where' : 'which';
  const bins = new Set();
  for (const t of TARGETS) for (const b of (t.bins || [])) bins.add(b);
  for (const bin of bins) {
    try {
      execFileSync(whichCmd, [bin], { stdio: 'ignore' });
      for (const t of TARGETS) if ((t.bins || []).includes(bin)) found.add(t.id);
    } catch { /* not installed */ }
  }
  _installedCache = found;
  return found;
}

/**
 * Compute the detected target set for a repo (before persistence).
 * Always includes the canonical AGENTS.md. Structural CI targets are only
 * enabled by a real signal (a repo without .github/ should not get a workflow).
 *
 * @param opts.useInstalled include machine-installed hints (default false — keep
 *   the portable default deterministic; init may pass true to seed richer).
 */
function detectTargets(cwd, opts = {}) {
  const { toolOwned, byId } = staticSignals(cwd);
  const installed = opts.useInstalled ? installedTools() : new Set();

  const ids = new Set(['agents-md']); // canonical, universal
  for (const id of toolOwned) ids.add(id);
  // Installed tools that ALSO have a file signal are already in; a bare install
  // with no repo signal is reported but not auto-enabled (avoid writing files a
  // repo never asked for). Claude Code is the one exception worth enabling on a
  // bare install, since CLAUDE.md is how it reads anything at all.
  if (installed.has('claude')) ids.add('claude');

  return {
    targets: [...ids],
    signals: { static: byId, installed: [...installed] },
  };
}

function configPath(cwd) {
  return path.join(cwd, CONFIG_REL);
}

function readConfig(cwd) {
  try {
    return JSON.parse(fs.readFileSync(configPath(cwd), 'utf-8'));
  } catch {
    return null;
  }
}

function writeConfig(cwd, cfg) {
  const { atomicWrite } = require('./atomic-write');
  atomicWrite(configPath(cwd), JSON.stringify(cfg, null, 2) + '\n');
}

/**
 * Resolve the target set `crag compile` (no --target) should build.
 *
 *   - If `.crag/config.json` has a `targets` array and !refresh → use it
 *     (authoritative, reproducible, user-editable).
 *   - Else detect, persist, and return. crag has not generated anything yet on
 *     a first run, so the only agent files present are the user's real tools →
 *     accurate seed. This is the detect-once-then-persist contract that also
 *     prevents crag's own output from re-triggering detection.
 *
 * @returns { targets, source: 'config'|'detected', signals? }
 */
function resolveTargets(cwd, opts = {}) {
  if (!opts.refresh) {
    const cfg = readConfig(cwd);
    if (cfg && Array.isArray(cfg.targets) && cfg.targets.length > 0) {
      return { targets: cfg.targets.filter((id) => getTarget(id)), source: 'config' };
    }
  }
  const det = detectTargets(cwd, opts);
  const cfg = readConfig(cwd) || {};
  writeConfig(cwd, {
    ...cfg,
    targets: det.targets,
    detected: det.signals,
    updatedAt: new Date().toISOString(),
  });
  return { targets: det.targets, source: 'detected', signals: det.signals };
}

module.exports = {
  staticSignals,
  installedTools,
  detectTargets,
  resolveTargets,
  readConfig,
  writeConfig,
  configPath,
  isCragGenerated,
  CONFIG_REL,
};
