'use strict';

/**
 * migrate-guard.js — refuse the compile-without-migrate footgun (crag #3615).
 *
 * Once a repo has `.crag/governance.gen.md` (its first `crag distill`),
 * `crag compile` switches to compose mode. If no `.crag/governance.src.md` seed
 * exists, the composed artifact carries ONLY the .gen layer and OVERWRITES a
 * rich hand-maintained `.claude/governance.md` with a near-empty file — silent
 * loss of every gate/security/branch rule. This guard turns that into a clear
 * refusal pointing at `crag distill --migrate` (which seeds the .src).
 */

const fs = require('fs');
const { layerPaths, artifactPath } = require('../governance/layer-paths');
const { cliError, EXIT_USER } = require('../cli-errors');

// A governance.md that is itself a compose artifact is safe to recompose over
// (idempotent). Detect that so the guard only protects hand-maintained files.
const COMPOSE_ARTIFACT_MARKERS = [
  'GENERATED by `crag compose`',
  'GENERATED by crag compose',
  '<!-- crag:composed -->',
];

function looksHandMaintained(text) {
  if (COMPOSE_ARTIFACT_MARKERS.some((m) => text.includes(m))) return false;
  return (
    text.trim().length > 400 ||
    /##\s*(Quality\s+)?Gates\b/i.test(text) ||   // crag's "## Gates" or "## Quality Gates"
    /##\s*Security\b/i.test(text) ||
    /^\s*-\s+`/m.test(text)
  );
}

/**
 * Exit with a clear message if composing now would gut a hand-maintained
 * governance.md. No-op in every safe case (legacy non-composed repos, repos
 * with a .src seed, empty/trivial or already-composed governance.md).
 */
function assertMigrateSafe(cwd) {
  const paths = layerPaths(cwd);
  if (!fs.existsSync(paths.projectGen)) return;   // no .gen → legacy compile, safe
  if (fs.existsSync(paths.projectSrc)) return;    // seeded → safe

  let existing;
  try { existing = fs.readFileSync(artifactPath(cwd), 'utf-8'); }
  catch { return; }                               // no governance.md → nothing to lose

  if (!looksHandMaintained(existing)) return;

  cliError(
    'refusing to compose — this would erase your hand-maintained governance.\n\n' +
    '  .crag/governance.gen.md exists but .crag/governance.src.md does not, so\n' +
    '  composing would OVERWRITE .claude/governance.md with a near-empty artifact\n' +
    '  (every gate/security/branch rule lost — crag #3615).\n\n' +
    '  Seed the composed model first:\n\n' +
    '      crag distill --migrate      # copies governance.md → .crag/governance.src.md\n\n' +
    '  then re-run `crag compile`. Your rules will be preserved and composed with\n' +
    '  the distilled principles.',
    EXIT_USER
  );
}

module.exports = { assertMigrateSafe, looksHandMaintained };
