'use strict';

const path = require('path');
const { atomicWrite } = require('./atomic-write');
const { preserveCustomSections } = require('./preserve');
const { buildAgentsMdContent } = require('./agents-md');

/**
 * satellite.js — the ONE renderer for every satellite-class target.
 *
 * Replaces nine bespoke flat-markdown generators (claude/gemini/cline/zed/
 * amazonq/aider/junie/goose/kiro), each of which re-rendered the same
 * governance substance under ~60-90 lines of hand-written boilerplate. A
 * satellite now produces one of three shapes, decided by its registry entry
 * (src/compile/targets.js) and whether AGENTS.md is part of the same run:
 *
 *   import  → a thin stub whose only job is to pull in AGENTS.md via the tool's
 *             native import directive (Claude Code `@AGENTS.md`).
 *   native  → NOTHING when AGENTS.md is in the run (the tool reads AGENTS.md
 *             itself; a duplicate would bloat context or shadow the canonical).
 *             Standalone (no agents-md in the run) → a self-contained mirror so
 *             an explicit `--target <id>` still yields a usable file.
 *   mirror  → a full, clearly-labeled copy of the AGENTS.md body (same content
 *             renderer → can never drift), for tools that read neither AGENTS.md
 *             nor an import.
 *
 * The mirror body comes from buildAgentsMdContent() — the single source of
 * agent-rule content shared with the canonical AGENTS.md target.
 */

/**
 * Decide what a satellite should emit given the run context.
 * Returns 'import' | 'mirror' | 'skip'.
 */
function satelliteAction(entry, agentsMdInRun) {
  if (entry.agentsMd === 'import') return agentsMdInRun ? 'import' : 'mirror';
  if (entry.agentsMd === 'native') return agentsMdInRun ? 'skip' : 'mirror';
  return 'mirror'; // agentsMd === 'mirror'
}

function importStub(entry, parsed, importRef) {
  const name = parsed.name || 'project';
  return [
    `# ${path.basename(entry.file, path.extname(entry.file))} — ${name}`,
    '',
    `> Generated by [crag](https://crag.sh). Canonical rules live in AGENTS.md (imported below). Regenerate: \`crag compile --target ${entry.id}\`.`,
    '',
    importRef,
    '',
  ].join('\n');
}

function mirrorDoc(entry, parsed) {
  const name = parsed.name || 'project';
  const note = `> GENERATED MIRROR of AGENTS.md by [crag](https://crag.sh) — **AGENTS.md is the canonical source.** ${entry.howReads || ''} Regenerate: \`crag compile --target ${entry.id}\`.`;
  return buildAgentsMdContent(parsed, {
    title: `# ${entry.label || entry.id} — ${name}`,
    note,
  });
}

/**
 * Render one satellite target.
 *
 * @param entry  registry entry (targets.js)
 * @param parsed parsed governance
 * @param ctx    { cwd, agentsMdInRun, importRef? }
 *   - agentsMdInRun: is the canonical agents-md target part of this compile run?
 *   - importRef: import directive to use (default entry.importLine, e.g.
 *     `@AGENTS.md`; --global passes an absolute `@~/.agents/AGENTS.md`).
 * @returns { id, file, action, outPath } — action ∈ 'import'|'mirror'|'skip'
 */
function renderSatellite(entry, parsed, ctx = {}) {
  const cwd = ctx.cwd || process.cwd();
  const action = satelliteAction(entry, !!ctx.agentsMdInRun);
  const outPath = path.join(cwd, entry.file);

  if (action === 'skip') {
    console.log(`  \x1b[90m○\x1b[0m ${entry.file} \x1b[2m(${entry.label} reads AGENTS.md — no file needed)\x1b[0m`);
    return { id: entry.id, file: entry.file, action, outPath: null };
  }

  const content = action === 'import'
    ? importStub(entry, parsed, ctx.importRef || entry.importLine || '@AGENTS.md')
    : mirrorDoc(entry, parsed);

  const final = preserveCustomSections(outPath, content, 'markdown');
  atomicWrite(outPath, final);
  console.log(`  \x1b[32m✓\x1b[0m ${entry.file}${action === 'import' ? ' \x1b[2m(→ AGENTS.md)\x1b[0m' : ''}`);
  return { id: entry.id, file: entry.file, action, outPath };
}

module.exports = { renderSatellite, satelliteAction };
