'use strict';

const path = require('path');
const { flattenGatesRich } = require('../governance/parse');
const { atomicWrite } = require('./atomic-write');
const { preserveCustomSections } = require('./preserve');
const { groupGatesByPath, pathToGlob, pathToFilename } = require('./path-groups');

/**
 * Compile governance.md to Windsurf rules.
 * Output: .windsurf/rules/governance.md (+ per-path files)
 *
 * Windsurf (by Codeium) is an AI-native IDE with a Cascade agent mode.
 * The current format uses `.windsurf/rules/*.md` with YAML frontmatter
 * specifying trigger mode, description, and optional globs.
 * Legacy `.windsurfrules` is still supported but deprecated.
 * Total budget: 12,000 characters across all workspace rules.
 *
 * Reference:
 *   https://docs.windsurf.com/windsurf/cascade/memories
 */
function generateWindsurf(cwd, parsed) {
  const { root, scoped } = groupGatesByPath(parsed.gates);

  // Root gates for the main file
  const rootGates = Object.keys(scoped).length > 0 ? root : flattenGatesRich(parsed.gates);
  const gatesList = rootGates.length === 0
    ? '(none defined)'
    : rootGates
        .map((g, i) => {
          const prefix = g.classification !== 'MANDATORY' ? ` [${g.classification}]` : '';
          const scope = g.path ? ` (in ${g.path})` : '';
          return `${i + 1}. \`${g.cmd}\`${scope}${prefix}`;
        })
        .join('\n');

  const securityBlock = parsed.security
    ? `- ${parsed.security.split('\n').filter(l => l.trim()).join('\n- ')}`
    : '- **No secrets.** Reject any code matching `sk_live`, `sk_test`, `AKIA`, or plaintext credentials.';

  const commitLine = parsed.commitConvention === 'conventional'
    ? `- **Conventional commits.** Every commit must follow \`<type>(<scope>): <description>\`.${parsed.commitTrailer ? `\n- **Commit trailer:** ${parsed.commitTrailer}` : ''}`
    : '- Follow the project commit conventions.';

  const content = `---
trigger: always_on
description: Governance rules for ${parsed.name || 'project'} — compiled from governance.md by crag
---

# Windsurf Rules — ${parsed.name || 'project'}

Generated from governance.md by crag. Regenerate: \`crag compile --target windsurf\`

## Project

${parsed.description || '(No description)'}
${parsed.stack.length > 0 ? `\n**Stack:** ${parsed.stack.join(', ')}` : ''}

## Runtimes

${parsed.runtimes.join(', ') || 'polyglot — detected at runtime'}

## Cascade Behavior

When Windsurf's Cascade agent operates on this project:

- **Always read governance.md first.** It is the single source of truth for quality gates and policies.
- **Run all mandatory gates before proposing changes.** Stop on first failure.
- **Respect classifications.** OPTIONAL gates warn but don't block. ADVISORY gates are informational.
- **Respect path scopes.** Gates with a \`path:\` annotation must run from that directory.
- **No destructive commands.** Never run rm -rf, dd, DROP TABLE, force-push to main, curl|bash, docker system prune.
${securityBlock}
${commitLine}

## Quality Gates (run in order)

${gatesList}

## Rules of Engagement

1. **Minimal changes.** Don't rewrite files that weren't asked to change.
2. **No new dependencies** without explicit approval.
3. **Prefer editing** existing files over creating new ones.
4. **Always explain** non-obvious changes in commit messages.
5. **Ask before** destructive operations (delete, rename, migrate schema).

---

**Tool:** crag — https://www.npmjs.com/package/@whitehatd/crag
`;

  const outPath = path.join(cwd, '.windsurf', 'rules', 'governance.md');
  // Windsurf .md files have YAML frontmatter — preservation markers would break
  // parsing. Users who need custom rules should create additional .md files.
  atomicWrite(outPath, content);
  console.log(`  \x1b[32m✓\x1b[0m ${path.relative(cwd, outPath)}`);

  // Per-path files (trigger: glob)
  for (const [scopePath, gates] of Object.entries(scoped)) {
    const sectionName = gates[0].section;
    const fileName = pathToFilename(scopePath);
    const glob = pathToGlob(scopePath);

    const scopedGatesList = gates
      .map((g, i) => {
        const prefix = g.classification !== 'MANDATORY' ? ` [${g.classification}]` : '';
        return `${i + 1}. \`${g.cmd}\`${prefix}`;
      })
      .join('\n');

    const scopedContent = `---
trigger: glob
globs: "${glob}"
description: ${sectionName} gates scoped to ${scopePath}
---

# ${sectionName.charAt(0).toUpperCase() + sectionName.slice(1)} — ${parsed.name || 'project'}

> Scoped to \`${scopePath}\`. Generated by crag.

## Quality Gates

${scopedGatesList}
`;

    const scopedPath = path.join(cwd, '.windsurf', 'rules', `${fileName}.md`);
    atomicWrite(scopedPath, scopedContent);
    console.log(`  \x1b[32m✓\x1b[0m ${path.relative(cwd, scopedPath)}`);
  }
}

module.exports = { generateWindsurf };
