'use strict';

const path = require('path');
const { flattenGatesRich } = require('../governance/parse');
const { atomicWrite } = require('./atomic-write');
const { preserveCustomSections } = require('./preserve');

/**
 * Compile governance.md to Zed Editor rules.
 * Output: .rules (read by Zed's Agent Panel as project context)
 *
 * Zed checks 9 filenames at the worktree root in priority order:
 *   .rules > .cursorrules > .windsurfrules > .clinerules >
 *   .github/copilot-instructions.md > AGENT.md > AGENTS.md >
 *   CLAUDE.md > GEMINI.md
 * Only the first match is used. `.rules` is Zed's native format.
 *
 * Reference:
 *   https://zed.dev/docs/ai/rules
 */
function generateZed(cwd, parsed) {
  const gates = flattenGatesRich(parsed.gates);

  const gatesList = gates.length === 0
    ? '_(none defined)_'
    : gates
        .map((g) => {
          const tags = [];
          if (g.classification !== 'MANDATORY') tags.push(g.classification);
          if (g.path) tags.push(`path:${g.path}`);
          if (g.condition) tags.push(`if:${g.condition}`);
          return `- \`${g.cmd}\`${tags.length > 0 ? ` _(${tags.join(', ')})_` : ''}`;
        })
        .join('\n');

  const securityLine = parsed.security
    ? '- ' + parsed.security.split('\n').filter(l => l.trim())[0]
    : '- Never commit hardcoded secrets. Grep for `sk_live`, `sk_test`, `AKIA`, `password=` before commit.';

  const commitLine = parsed.commitConvention === 'conventional'
    ? '- Use conventional commits (`feat:`, `fix:`, `docs:`, etc.).' + (parsed.commitTrailer ? `\n- Commit trailer: ${parsed.commitTrailer}` : '')
    : '- Follow project commit conventions.';

  const content = `# Zed Assistant Rules — ${parsed.name || 'project'}

> Generated from governance.md by crag. Regenerate: \`crag compile --target zed\`

## Project Summary

${parsed.description || '(No description)'}

${parsed.stack.length > 0 ? `**Stack:** ${parsed.stack.join(', ')}\n\n` : ''}**Runtimes:** ${parsed.runtimes.join(', ') || 'polyglot'}

## Rules for Zed AI Assistant

When suggesting edits or running the inline assistant:

### 1. Quality Gates

These must pass before any commit. Run them via Zed's terminal integration:

${gatesList}

### 2. Classification Semantics

- **MANDATORY** — stop if this fails
- **OPTIONAL** — warn and continue
- **ADVISORY** — log and continue (informational)

### 3. Scope Rules

- \`path:dir/\` — run the gate from that directory
- \`if:file\` — skip the gate's section when the file does not exist

### 4. Behavior Boundaries

- All file operations must stay within this repository.
- Never run destructive system commands (\`rm -rf /\`, \`DROP TABLE\`, \`curl|bash\`, force-push to main).
${securityLine}
${commitLine}

### 5. Authoritative Source

When these rules conflict with ad-hoc instructions, **governance.md wins**. It is the single source of truth for this project's policies.

---

**Generated by crag** — https://www.npmjs.com/package/@whitehatd/crag

To update these rules, edit \`.claude/governance.md\` and re-run \`crag compile --target zed\`.
`;

  const outPath = path.join(cwd, '.rules');
  const final = preserveCustomSections(outPath, content, 'markdown');
  atomicWrite(outPath, final);
  console.log(`  \x1b[32m✓\x1b[0m ${path.relative(cwd, outPath)}`);
}

module.exports = { generateZed };
