#!/usr/bin/env bash
set -euo pipefail

# fix-pr.sh — Clone a repo, generate governance + AI configs, prepare a PR branch.
#
# Usage:
#   ./scripts/fix-pr.sh owner/repo
#
# Example:
#   ./scripts/fix-pr.sh tauri-apps/tauri
#
# What it does:
#   1. Shallow-clones the repo to a temp directory
#   2. Runs crag analyze + compile --target all
#   3. Creates branch add-ai-governance
#   4. Commits generated files
#   5. Prints the PR body for review
#
# After reviewing, cd into the temp dir and run:
#   git remote set-url origin https://github.com/YOUR_FORK/REPO.git
#   git push -u origin add-ai-governance
#   gh pr create --title "Add AI agent governance" --body-file /dev/stdin <<< "$(cat)"

REPO="${1:-}"

if [ -z "$REPO" ]; then
  echo "Usage: $0 owner/repo"
  echo "Example: $0 tauri-apps/tauri"
  exit 1
fi

# Validate format
if ! echo "$REPO" | grep -qE '^[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+$'; then
  echo "Error: invalid repo format — use owner/repo"
  exit 1
fi

OWNER="${REPO%%/*}"
NAME="${REPO##*/}"
TMPDIR=$(mktemp -d)
CLONE_DIR="$TMPDIR/$NAME"

echo "=== fix-pr: $REPO ==="
echo ""

# 1. Clone
echo "[1/5] Cloning $REPO..."
git clone --depth 1 "https://github.com/$REPO.git" "$CLONE_DIR" 2>&1 | tail -1
echo "      Cloned to $CLONE_DIR"
echo ""

# 2. Analyze
echo "[2/5] Running crag analyze..."
(cd "$CLONE_DIR" && crag analyze --no-install-skills 2>&1 | tail -3)
echo ""

# 3. Compile
echo "[3/5] Running crag compile --target all..."
(cd "$CLONE_DIR" && crag compile --target all 2>&1 | tail -3)
echo ""

# 4. Branch + commit
echo "[4/5] Creating branch and committing..."
(
  cd "$CLONE_DIR"
  git checkout -b add-ai-governance
  git add -A
  git commit -m "feat: add AI agent governance configs

Generated by crag (https://crag.sh) from existing CI config.
One governance.md compiled to 14 AI tool configs.

Co-Authored-By: crag <noreply@crag.sh>" --quiet
)
echo "      Branch: add-ai-governance"
echo "      Files staged:"
(cd "$CLONE_DIR" && git diff --stat HEAD~1 | tail -5)
echo ""

# 5. Print PR body
echo "[5/5] PR body (copy below the line):"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
cat <<'PRBODY'
## Add AI agent governance

AI coding tools (Claude Code, Cursor, Copilot, Codex, Gemini) work better when
they know your repo's actual rules. This PR adds governance configs generated
from your existing CI pipeline — no manual authoring needed.

### What's included

Generated by [crag](https://crag.sh) from your CI config:

- `CLAUDE.md` — Claude Code instructions
- `AGENTS.md` — Universal standard (Codex, Aider, 60K+ repos)
- `.cursor/rules/governance.mdc` — Cursor rules
- `.github/copilot-instructions.md` — GitHub Copilot
- `GEMINI.md` — Gemini CLI
- Plus 9 more tool configs

All files are deterministically generated from a single `governance.md` source
file. When your CI changes, run `npx @whitehatd/crag` to regenerate.

### Why this matters

Your repo was [audited on the crag leaderboard](https://crag.sh/leaderboard) and
currently has **zero AI agent configs**. This means every AI tool working on your
codebase is guessing at your quality standards instead of following them.

### Maintenance

Add a pre-commit hook to keep configs in sync:
```bash
npx @whitehatd/crag hook install
```

Or add CI drift detection:
```yaml
# .github/workflows/crag-audit.yml
- uses: WhitehatD/crag-audit-action@v1
```

---
Generated with [crag](https://crag.sh) — one governance.md, 14 tool configs, no drift.
PRBODY
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "=== Done ==="
echo ""
echo "Next steps:"
echo "  cd $CLONE_DIR"
echo "  # Fork the repo on GitHub, then:"
echo "  git remote set-url origin https://github.com/YOUR_USER/$NAME.git"
echo "  git push -u origin add-ai-governance"
echo "  gh pr create --repo $REPO --title 'Add AI agent governance' --body-file pr-body.md"
